### PR TITLE
Update ShowHiddenChannelsV2.plugin.js

### PR DESCRIPTION
**Pull request by Eden333**
fixed version number on the top, to make plugin work

### CODE REVIEW

**Comment by osc86** [comment]
Installed the V2 Plugin and replaced the 0BDFDB files. Works fine, without changing the version number. 🤷

**Comment by zhongli0409** [comment]
> Installed the V2 Plugin and replaced the 0BDFDB files. Works fine, without changing the version number. 🤷

how did u do that

**Comment by Eden333** [comment]
> Installed the V2 Plugin and replaced the 0BDFDB files. Works fine, without changing the version number. 🤷

no idea about the lib if I had to change anything. I simply fixed the version to match the one below and it started working for me

**Comment by Saalvage** [comment]
Since the name is different this shouldn't affect anything.. But if it does, I'll merge it anyways because it definitely won't break things!

**Pull request merged**
